#!/bin/bash
# chkconfig: 2345 55 25
# description: CyberDog Joystick Service

### BEGIN INIT INFO
# Provides:          joystick
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts bt
# Description:       starts the bt
### END INIT INFO