#!/bin/bash
# chkconfig: 2345 55 25
# description: CyberDog Joystick Service

### BEGIN INIT INFO
# Provides:          joystick
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts joystick
# Description:       starts joystick
### END INIT INFO

topic_name=
while [ ! $topic_name ] 
do
    topic_name=${ros2 topic list | grep ip_notify}
done

ros2 topic pub --once ${ros2 topic list | grep ip_notify} std_msgs/msg/String "data: 127.0.0.1:127.0.0.1"

python3 /home/mi/Desktop/cyberdog/joystick.py